LITReview/urls.py
from django.contrib import admin
from django.urls import path, include

# imports to config images uploading
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("authentication.urls")),
    path("", include("review.urls")),
]

# images url configuration
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("bands/", views.band_list, name="band-list"),
    # ajouter ce motif sous notre autre motif de groupes
    path("bands/<int:band_id>/", views.band_detail, name="band-detail"),
    path("about-us/", views.about),
    path("listings/", views.listing_list, name="listing-list"),
    path("listings/<int:listing_id>/", views.listing_detail, name="listing-detail"),
    path("contact-us/", views.contact, name="contact"),
    path("email-sent/", views.email, name="email-sent"),
]

review/urls.py
from django.urls import path

from review.views import (
    home,
    posts,
    ranking,
    search,
    forbidden_permission,
    ticket_detail,
    ticket_create,
    ticket_update,
    ticket_delete,
    review_detail,
    ticket_self_review_create,
    self_review_create,
    review_create,
    review_delete,
    self_review_delete,
    review_update,
    self_review_update,
    relation,
    relation_delete,
    relation_block
)


urlpatterns = [
    # ticket & review
    path("home/", home, name="home"),
    path("posts/", posts, name="posts"),
    path("ranking/", ranking, name="ranking"),
    path("search/", search, name="search"),
    path("forbidden_permission/", forbidden_permission, name="forbidden_permission"),
    path(
        "reviews/ticket_self_review_create/",
        ticket_self_review_create,
        name="ticket_self_review_create",
    ),
    # ticket
    path("tickets/<int:ticket_id>/", ticket_detail, name="ticket_detail"),
    path("tickets/create/", ticket_create, name="ticket_create"),
    path("tickets/<int:ticket_id>/update/", ticket_update, name="ticket_update"),
    path("tickets/<int:ticket_id>/delete/", ticket_delete, name="ticket_delete"),
    # review
    path("reviews/<int:review_id>/", review_detail, name="review_detail"),
    path(
        "reviews/<int:review_id>/self_review_create/",
        self_review_create,
        name="self_review_create",
    ),
    path("reviews/<int:review_id>/review_create/", review_create, name="review_create"),
    path("reviews/<int:review_id>/review_delete/", review_delete, name="review_delete"),
    path(
        "reviews/<int:review_id>/self_review_delete/",
        self_review_delete,
        name="self_review_delete",
    ),
    path("reviews/<int:review_id>/review_update/", review_update, name="review_update"),
    path(
        "reviews/<int:review_id>/self_review_update/",
        self_review_update,
        name="self_review_update",
    ),
    # relation
    path("relations/", relation, name="relation"),
    path("relations/<int:relation_id>/delete", relation_delete, name="relation_delete"),
    path("relations/<int:relation_id>/block", relation_block, name="relation_block"),
]

merchex/listings/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator


class Band(models.Model):
    class Genre(models.TextChoices):
        """sert pour la création d'un liste à dérouler ou l'on peut choisir uniquement un genre"""

        HIP_HOP = "HH"
        SYNTH_POP = "SP"
        ALTERNATIVE_ROCK = "AR"
        RAP = "RP"

    name = models.fields.CharField(max_length=100)
    genre = models.fields.CharField(choices=Genre.choices, max_length=5)
    biography = models.fields.CharField(max_length=1000)
    year_formed = models.fields.IntegerField(
        validators=[MinValueValidator(1900), MaxValueValidator(2021)]
    )
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)

    def __str__(self):
        return f"{self.name}"


class Listing(models.Model):
    class Type(models.TextChoices):
        """sert pour la création d'un liste à dérouler ou l'on peut choisir uniquement un genre"""

        RECORDS = "RS"
        CLOTHINGS = "CS"
        POSTERS = "PS"
        MISCELLEANEOUS = "MS"

    title = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=1000)
    sold = models.fields.BooleanField(default=False)
    year_formed = models.fields.IntegerField(
        validators=[MinValueValidator(1900), MaxValueValidator(2023)],
        null=True,
        blank=True,
    )

    type = models.fields.CharField(choices=Type.choices, max_length=5)
    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)

merchex/listings/forms.py
# listings/forms.py

from django import forms


class ContactUsForm(forms.Form):
    """création du formulaire de contact"""

    name = forms.CharField(required=False)
    email = forms.EmailField()
    message = forms.CharField(max_length=1000)

merchex/listings/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core.mail import send_mail
from django.shortcuts import redirect

from listings.models import Band, Listing
from listings.forms import ContactUsForm


def contact(request):
    if request.method == "POST":
        # créer une instance de notre formulaire et le remplir avec
        # les données POST
        form = ContactUsForm(request.POST)

        if form.is_valid():
            """si le formulaire est valide nous envoyons un email !"""

            send_mail(
                subject=f'Message from {form.cleaned_data["name"] or "anonyme"} via MerchEx Contact Us form',
                message=form.cleaned_data["message"],
                from_email=form.cleaned_data["email"],
                recipient_list=["admin@merchex.xyz"],
            )
            """ redirige vers la page "email envoyé" pour éviter les doublon de POST """
            return redirect("email-sent")
            #  créer l'url, le template et la vue de email-sent !

    # si le formulaire n'est pas valide, nous laissons l'exécution continuer jusqu'au return
    # ci-dessous et afficher à nouveau le formulaire (avec des erreurs).

    else:
        # ceci doit être une requête GET, donc créer un formulaire vide
        form = ContactUsForm()

    return render(request, "listings/contact.html", {"form": form})


def email(request):
    return render(request, "listings/email.html")


def band_list(request):
    """liste toutes les entités par leur champs name"""

    bands = Band.objects.all()

    return render(request, "listings/band_list.html", {"bands": bands})


def band_detail(request, band_id):  # notez le paramètre id supplémentaire
    """list tous les champs d'une seule entité"""

    band = Band.objects.get(id=band_id)
    return render(
        request, "listings/band_detail.html", {"band": band}
    )  # nous mettons à jour cette ligne pour passer le groupe au gabarit


def about(request):
    return render(request, "listings/about.html", {"tel": "06.95.13.95.94"})


def listing_list(request):
    """liste toutes les entités par leur champs name"""

    listings = Listing.objects.all()
    return render(request, "listings/listing_list.html", {"listings": listings})


def listing_detail(request, listing_id):  # notez le paramètre id supplémentaire
    """list tous les champs d'une seule entité"""

    listing = Listing.objects.get(id=listing_id)
    return render(
        request, "listings/listing_detail.html", {"listing": listing}
    )  # nous mettons à jour cette ligne pour passer le groupe au gabarit

merchex/listings/templates/listings/about.html
{% extends 'listings/base.html' %} 

{% block content %}
    <h1>About us... tel us {{tel}}</h1>
    {% endblock %}

merchex/listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %} {% block content %}

<h2>{{ band.name }}</h2>

<ul>
  <!-- .get_genre_displaypermet d'afficher sur le site la clé 
        et non la valeur abrégé stocké dansla BDD en de liste de valeur -->
  <li>Genre : {{ band.get_genre_display }}</li>
  <li>Année de formation : {{ band.year_formed }}</li>
  <li>Actif : {{ band.active|yesno }}</li>
    {% if band.official_homepage %}
    <li><a href="{{ band.official_homepage }}">{{ band.official_homepage }}</a></li>
    {% endif %}
</ul>

<p>{{ band.biography }}</p>

<a href="{% url 'band-list' %}">Retour à liste des groupes</a>

{% endblock %}

merchex/listings/templates/listings/band_list.html
{% extends 'listings/base.html' %} 

{% block content %}

<h1>Bands</h1>

<ul>
  {% for band in bands %}
  <li><a href="{% url 'band-detail' band.id %}">{{ band.name }}</a></li>
  {% endfor %}
</ul>

{% endblock %}

merchex/listings/templates/listings/base.html
{% load static %}
<html>
  <head>
    <title>Merchex</title>
    <link rel="stylesheet" href="{% static 'listings/styles.css' %}" />
  </head>
  <body>
    <nav>
      <a href="{% url 'band-list' %}">Bands</a>
      <a href="{% url 'listing-list' %}">Listings</a>
      <a href="{% url 'contact' %}">Contact</a>
    </nav>

    {% block content %}{% endblock %}
  </body>
</html>

merchex/listings/templates/listings/contact.html
{% extends 'listings/base.html' %} 

{% block content %}
<p>Nous sommes là pour vous aider.</p>

<form action="" method="post" novalidate>
<!-- génére automatiquement les balise input ! -->
{% csrf_token %}
<!-- {{ form }} pour afficher
     le formulaire sur la même ligne -->
     {{ form.as_p }} <!--pour afficher les formulaire en pile-->
<input type="submit" value="Envoyer">
</form>
<form action=""></form>
{% endblock %}

merchex/listings/templates/listings/email.html
{% extends 'listings/base.html' %} 

{% block content %}
<h1><br>Email Envoyé !</h1>

{% endblock %}

merchex/listings/templates/listings/listing_detail.html
{% extends 'listings/base.html' %} {% block content %}

<h2>{{ listing.title }}</h2>

<ul>
  <!-- .get_genre_displaypermet d'afficher sur le site la clé 
        et non la valeur abrégé stocké dansla BDD en de liste de valeur -->
  <li>Type : {{ listing.get_type_display }}</li>
  <li>Année de formation : {{ listing.year_formed }}</li>
  <li>Sold : {{ listing.sold|yesno }}</li>

  <li>Band : {{ listing.band }}</li>

</ul>

<p>{{ listing.description }}</p>

<a href="{% url 'listing-list' %}">Retour à liste des listings</a>

{% endblock %}

merchex/listings/templates/listings/listing_list.html
{% extends 'listings/base.html' %} 

{% block content %}
<h1>Listings</h1>
<ul>
  {% for listing in listings %}
  <li><a href="{% url 'listing-detail' listing.id %}">{{listing.title}}</a></li>
  {% endfor %}
</ul>
{% endblock %}